# Variables for DLVMAMXBRBSS01
---
# Add host-specific variables below
#
########## Feature Flags ##########
deploy_telegraf_redis: false
deploy_telegraf_postgres: false
deploy_telegraf_infra: false
deploy_mysql_replica_status_monitor: false
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false
deploy_mysql_slowquery_script: false
deploy_nginx: false

apps:
  - name: "Java"
    match: "java"
    type: "pattern"
  - name: "BSS"
    match: "/opt/webservers/bss"
    type: "pattern"

ports:
  - ip: 127.0.0.1
    port: 8080
    name: Java
  - ip: 127.0.0.1
    port: 8005
    name: Java
  - ip: 127.0.0.1
    port: 8086
    name: java
  - ip: 10.221.87.218
    port: 3306
    name: MysqlDB
  - ip: 10.221.81.41
    port: 6667
    name: NN1
  - ip: 10.221.81.42
    port: 6667
    name: NN2
  - ip: 10.221.81.43
    port: 6667
    name: NN3
  - ip: 10.221.93.183
    port: 30666
    name: Java
