# Variables for DLVMAMXORA4
# IP 10.221.87.133
---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "ORACLE"
    match: "ora_pmon_RWDB"
    type: "pattern"

# Application ports for DLVMAMXORA4
ports:
  - ip: "10.221.87.133"
    port: 1521
    name: "ORACLE"
 