# Variables for DLVMAMXNC01
# IP 10.221.86.226
---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "downloadcenter"
    match: "downloadcenter.jar"
    type: "pattern"
 
  - name: "Java"
    match: "java"
    type: "pattern"
  
# Application ports for DLVMAMXNC01
ports:
  - ip: "127.0.0.1"
    port: 34467
    name: "pbx_exchange"

  - ip: "127.0.0.1"
    port: 8444
    name: "Java"
    
   - ip: "10.221.86.226"
    port: 9100
    name: "node_exporter"
       