# Variables for DLVMTMAMXK8SWORK07
# IP 10.221.92.188
---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "longhorn-engine"
    match: "longhorn-engine"
    type: "pattern"
  - name: "app.jar"
    match: "app.jar"
    type: "pattern"
  - name: "containerd"
    match: "containerd"
    type: "pattern"
 
# Application ports for DLVMTMAMXK8SWORK07
ports:
  - ip: "127.0.0.1"
    port: 10249
    name: "kube-proxy"

  - ip: "127.0.0.1"
    port: 10256
    name: "kube-proxy"

  - ip: "127.0.0.1"
    port: 10248
    name: "kubelet"

  - ip: "10.221.93.180"
    port: 10010
    name: "containerd"