# Variables for DLVMTMAMXHA01
# IP 10.221.92.190
---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "haproxy"
    match: "haproxy"
    type: "pattern"
    
  - name: "gsd-screensaver-proxy"
    match: "gsd-screensaver-proxy"
    type: "pattern"   
 
# Application ports for DLVMTMAMXHA01
ports:
  - ip: "10.221.93.190"
    port: 5432
    name: "haproxy"

  - ip: "127.0.0.1"
    port: 5433
    name: "haproxy"