# Variables for DLVMTMAMXMEXBSS08
# IP 10.221.92.174
---
# Add host-specific variables below
deploy_telegraf_redis: false
deploy_telegraf_postgres: false
deploy_telegraf_infra: false
deploy_mysql_replica_status_monitor: false
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false
deploy_mysql_slowquery_script: false
deploy_nginx: false
deploy_bssBypass_Check: false

apps:
  - name: "MexicoBSS3"
    match: "bss_1"
    type: "pattern"

# Application ports for DLVMTMAMXMEXBSS08
ports:
  - ip: "127.0.0.1"
    port: 8081
    name: "java-8448"

  - ip: "10.221.81.41"
    port: 6667
    name: "KAFKA1-STREAMING"

  - ip: "10.221.81.42"
    port: 6667
    name: "KAFKA2-STREAMING"

  - ip: "10.221.81.43"
    port: 6667
    name: "KAFKA3-STREAMING"

  - ip: "10.221.93.39"
    port: 3306
    name: "MYSQL"
