# Variables for DLVMAMXHMST01
---
# Add host-specific variables below
########## Feature Flags ##########
deploy_telegraf_redis: false
deploy_telegraf_postgres: false
deploy_telegraf_infra: false
deploy_mysql_replica_status_monitor: false
deploy_mysql_slowquery_script: false
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false
deploy_nginx: false

########## Application Monitoring ##########
apps:
  - name: "Apache_Oozie_Server"
    match: "apache.oozie.cli.OozieCLI"
    type: "pattern"
  - name: "Zookeeper"
    match: "org.apache.zookeeper.server"
    type: "pattern"
  - name: "NameNode"
    match: "Dproc_namenode"
    type: "pattern"
  - name: "Ambari"
    match: "ambari-agent"
    type: "pattern"
  - name: "Postgres"
    match: "postgres"
    type: "pattern"

########## Port Monitoring ##########
ports:
  - ip: 127.0.0.1
    port: 8030
    name: Yarn_Scheduler
  - ip: 127.0.0.1
    port: 8088
    name: Yarn_webUI
  - ip: 127.0.0.1
    port: 19888
    name: MapReduce_UI
  - ip: 127.0.0.1
    port: 10020
    name: Map_Reduce
  - ip: 127.0.0.1
    port: 50070
    name: HDFS_NN_UI
  - ip: 127.0.0.1
    port: 50090
    name: NN_Checkpoint
  - ip: 127.0.0.1
    port: 2181
    name: Zookeeper
  - ip: 127.0.0.1
    port: 8020
    name: NN_RPCclient
  - ip: 127.0.0.1
    port: 8050
    name: Yarn_RM
  - ip: 127.0.0.1
    port: 8670
    name: Ambari_Agent
  - ip: 127.0.0.1
    port: 8080
    name: Ambari_Server
  - ip: 127.0.0.1
    port: 5432
    name: Postgres

######## Remote #######
  - ip: 10.221.81.40
    port: 3888
    name: Ambari_Server
  - ip: 10.221.81.40
    port: 9441
    name: Ambari_HeartBeat
  - ip: 10.221.81.40
    port: 9000
    name: NN_IPC
  - ip: 10.221.81.40
    port: 8188
    name: Yarn_UI
