# Variables for DLVMTMAMXK8SWORK01
# IP 10.221.93.182
---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "kubelet"
    match: "kubelet"
    type: "pattern"
  - name: "kube-proxy"
    match: "kube-proxy"
    type: "pattern"
  - name: "nginx"
    match: "nginx"
    type: "pattern"
  - name: "longhorn"
    match: "longhorn"
    type: "pattern"
  - name: "calico"
    match: "calico"
    type: "pattern"

# Application ports for DLVMTMAMXK8SWORK01
ports:
  - ip: "127.0.0.1"
    port: 9099
    name: "calico"

  - ip: "127.0.0.1"
    port: 6444
    name: "rke2 agent"

  - ip: "10.221.93.179"
    port: 6443
    name: "kube-scheduler"
