# Variables for DLVMTMAMXETCD03
# IP 10.221.92.194
---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "etcd"
    match: "etcd"
    type: "pattern"
	
# Application ports for DLVMTMAMXETCD03
ports:
  - ip: "10.221.93.194"
    port: 2379
    name: "etcd"

  - ip: "10.221.93.193"
    port: 2380
    name: "etcd"