# Variables for DLVMAMXSABRDRA02
# IP 10.221.92.51
---
# Add host-specific variables below
deploy_telegraf_redis: false
deploy_telegraf_postgres: false
deploy_telegraf_infra: false
deploy_mysql_replica_status_monitor: false
deploy_mysql_slowquery_script: false
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: true
deploy_nginx: false

oracle_user: "RWUSER"
oracle_pass: "ROAMWARE"
oracle_db: "RWDB"
oracle_home: "/u01/app/oracle/product/11.2.4/client_1"

apps:
  - name: "BrazilDRA1"
    match: "DiameterRoutingAgent"
    type: "pattern"

# Application-related ports for DLVMAMXSABRDRA02
ports:
  - ip: "127.0.0.1"
    port: 4131
    name: "java"
