# Variables for DLVMAMXACONTOL02
# IP 10.221.86.128
---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "Node JS"
    match: "server.js"
    type: "pattern"
	
# Application ports for DLVMAMXACONTOL02
ports:
  - ip: "127.0.0.1"
    port: 8080
    name: "Node"

  - ip: "127.0.0.1"
    port: 3001
    name: "Node"