# Variables for DLVMTMAMXPOSTGDB02
# IP 10.221.92.156
---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "postgres"
    match: "postgres"
    type: "pattern"
 
# Application ports for DLVMTMAMXPOSTGDB02
ports:
  - ip: "127.0.0.1"
    port: 5432
    name: "postgres"

  - ip: "10.221.92.156"
    port: 46228
    name: "MXPOSTGDB02"