# Variables for DLVMAMXSABROCS02
# IP 10.221.92.71
---
# Add host-specific variables below
deploy_telegraf_redis: false
deploy_telegraf_postgres: false
deploy_telegraf_infra: false
deploy_mysql_replica_status_monitor: false
deploy_mysql_slowquery_script: false
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false
deploy_nginx: false
deploy_bssBypass_Check: true

#### Oracle DB details ######
oracle_home: /u01/app/oracle/product/11.2.4/client_1
db_user: RWUSER
db_pass: ROAMWARE
db_conn: RWDB

apps:
  - name: "Spread"
    match: "spread"
    type: "pattern"

  - name: "AirOCS"
    match: "AirOCSApp"
    type: "pattern"

  - name: "ApiService"
    match: "ApiServiceApp"
    type: "pattern"

  - name: "AirConsumer"
    match: "AirConsumerApp"
    type: "pattern"

# Application ports for DLVMAMXSABROCS02
ports:
  - ip: "127.0.0.1"
    port: 8060
    name: "java-8060"

  - ip: "127.0.0.1"
    port: 8070
    name: "java-8070"

  - ip: "127.0.0.1"
    port: 9116
    name: "app-9116"

  - ip: "10.221.81.41"
    port: 6667
    name: "KAFKA1-STREAMING"

  - ip: "10.221.81.42"
    port: 6667
    name: "KAFKA2-STREAMING"

  - ip: "10.221.93.74"
    port: 1521
    name: "ORACLE"
