# Variables for DLVMAMXOMBSSDB02
# IP 10.221.86.246
---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "mysql"
    match: "mysqld"
    type: "pattern"

# Application ports for DLVMAMXOMBSSDB02
ports:
  - ip: "10.221.86.246"
    port: 3306
    name: "mysql"
 