# Variables for DLVMAMXOCS01
# Add host-specific variables below

########## Feature Flags ##########
deploy_telegraf_redis: false
deploy_telegraf_postgres: false
deploy_telegraf_infra: false
deploy_mysql_replica_status_monitor: false
deploy_mysql_slowquery_script: false
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: true
deploy_nginx: false

apps:
  - name: "DRA"
    match: "DiameterRoutingAgent"
    type: "pattern"

oracle_user: "RWUSER"
oracle_pass: "ROAMWARE"
oracle_db: "RWDB"
oracle_home: "/u01/app/oracle/product/11.2.4/client_1"

ports:
  - ip: 127.0.0.1
    port: 3869
    name: DRA
  - ip: 127.0.0.1
    port: 3870
    name: DRA
  - ip: 127.0.0.1
    port: 3871
    name: DRA
  - ip: 127.0.0.1
    port: 20131
    name: OCS
  - ip: 127.0.0.1
    port: 4131
    name: unknown
  - ip: 127.0.0.1
    port: 1556
    name: Unknown
  - ip: 127.0.0.1
    port: 2049
    name: unknown
  - ip: 10.221.93.106
    port: 8086
    name: influxdb1
  - ip: 10.221.93.107
    port: 8086
    name: influxdb2
  - ip: 203.89.104.232
    port: 3868
    name: DRA
  - ip: 192.168.202.136
    port: 1556
    name: unknown
  - ip: 10.221.87.132
    port: 1521
    name: unknown
