# Variables for DLVMAMXSAMXDRA01
# IP 10.221.92.50
---
# Add host-specific variables below
deploy_telegraf_redis: false
deploy_telegraf_postgres: false
deploy_telegraf_infra: false
deploy_mysql_replica_status_monitor: false
deploy_mysql_slowquery_script: false
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false
deploy_nginx: false

oracle_user: "RWUSER"
oracle_pass: "ROAMWARE"
oracle_db: "RWDB"
oracle_home: "/u01/app/oracle/product/11.2.4/client_1"

apps:
  - name: "MexicoDRA2"
    match: "DiameterRoutingAgent"
    type: "pattern"

# Application ports for DLVMAMXSAMXDRA01
ports:
  - ip: "203.89.104.109"
    port: 3868
    name: "java-3868"

  - ip: "203.89.104.109"
    port: 3869
    name: "java-3869"

  - ip: "127.0.0.1"
    port: 8005
    name: "tomcat-shutdown"

  - ip: "127.0.0.1"
    port: 8080
    name: "java-8080"
    
  - ip: "10.221.93.73"
    port: 1521
    name: "ORACLE"
