# Variables for DLVMAMXAAASB01
# IP 10.221.86.117

---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "telegraf"
    match: "telegraf"
    type: "pattern"


  
# Application ports for DLVMAMXAAASB01
ports:
  - ip: "10.221.92.106"
    port: 8086
    name: "influxdb1"

  - ip: "10.221.92.107"
    port: 8086
    name: "influxdb2"

  - ip: "192.168.202.136"
    port: 1556
    name: "pbx_exchange"