# Variables for DLVMAMXGCLB01
---
# Add host-specific variables below
#
########## Feature Flags ##########
deploy_telegraf_redis: false
deploy_telegraf_postgres: false
deploy_telegraf_infra: false
deploy_mysql_replica_status_monitor: false
deploy_mysql_slowquery_script: false
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false
deploy_nginx: false

########## Application Monitoring ##########
apps:
  - name: "Nginx_Worker"
    match: "nginx: worker process"
    type: "pattern"
  - name: "Nginx_Master"
    match: "nginx: master process"
    type: "pattern"

########## Port Monitoring ##########
ports:
  - ip: 127.0.0.1
    port: 443
    name: nginx
  - ip: 10.221.86.110
    port: 8080
    name: nginx
  - ip: 127.0.0.1
    port: 8443
    name: nginx
  - ip: 127.0.0.1
    port: 9443
    name: nginx
  - ip: 127.0.0.1
    port: 8080
    name: nginx
  - ip: 203.89.104.248
    port: 8443
    name: nginx
  - ip: 10.221.86.111
    port: 8444
    name: nginx
  - ip: 10.221.86.115
    port: 8080
    name: unknown

