# Variables for DLVMAMXSMSC1
# IP 10.221.86.120
---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "CloudSIMSMSC"
    match: "CloudSIMSMSC"
    type: "pattern"

  - name: "jakarta-tomcat"
    match: "jakarta-tomcat"
    type: "pattern"

  - name: "watchdog"
    match: "watchdog"
    type: "pattern"

  - name: "spread"
    match: "spread"
    type: "pattern"


# Application ports for DLVMAMXSMSC1
ports:
  - ip: "127.0.0.1"
    port: 8005
    name: "java"

  - ip: "127.0.0.1"
    port: 42666
    name: "pbx_exchange"