# Variables for DLVMAMXGCLB01
# IP 10.221.86.110

---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "nginx"
    match: "nginx.conf"
    type: "pattern"

  - name: "nginx_tele"
    match: "nginx_tele.conf"
    type: "pattern"
    
  - name: "pbx_exchange"
    match: "pbx_exchange"
    type: "pattern"
        
  
# Application ports for DLVMAMXGCLB01
ports:
  - ip: "127.0.0.1"
    port: 8443
    name: "nginx: master"

  - ip: "127.0.0.1"
    port: 9443
    name: "nginx: master"
	
  - ip: "127.0.0.1"
    port: 1557
    name: "pbx_exchange"	
	