# Variables for DLVMTMAMXPOSTGDB03
# IP 10.221.92.157
---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "postgres"
    match: "postgres"
    type: "pattern"
 
# Application ports for DLVMTMAMXPOSTGDB03
ports:
  - ip: "127.0.0.1"
    port: 5432
    name: "postgres"

  - ip: "10.221.93.193"
    port: 2379
    name: "postgres"