# Variables for DLVMTMAMXHA02
# IP 10.221.92.191
---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "proxy"
    match: "haproxy"
    type: "pattern"

# Application ports for DLVMTMAMXHA02
ports:
  - ip: "127.0.0.1"
    port: 7000
    name: "haproxy"

  - ip: "127.0.0.1"
    port: 5432
    name: "haproxy"