# Variables forDLVMMAXALLBSSDB03
# IP 10.221.86.219
---
# Add host-specific variables below
deploy_telegraf_redis: false
deploy_telegraf_postgres: false
deploy_telegraf_infra: false
deploy_mysql_replica_status_monitor: false
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false
deploy_mysql_slowquery_script: false
deploy_nginx: false

apps:
  - name: "mysql"
    match: "mysql"
    type: "pattern"
 
# Application ports for DLVMMAXALLBSSDB03
ports:
  - ip: "127.0.0.1"
    port: 33060
    name: "mysqld"

  - ip: "127.0.0.1"
    port: 3306
    name: "mysqld"
    
  - ip: "10.221.86.219"
    port: 57210
    name: "LBSSDB03"    