# Variables for DLVMAMXAPI02
---
# Add host-specific variables below
#

########## Feature Flags ##########
deploy_telegraf_redis: false
deploy_telegraf_postgres: false
deploy_telegraf_infra: false
deploy_mysql_replica_status_monitor: false
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false
deploy_mysql_slowquery_script: false
deploy_nginx: false

########## Application Monitoring ##########
apps:
  - name: "Tomcat"
    match: "apache-tomcat"
    type: "pattern"

########## Port Monitoring ##########
ports:
  - ip: 127.0.0.1
    port: 8082
    name: tomcat_http
  - ip: 127.0.0.1
    port: 8444
    name: tomcat_https
  - ip: 10.221.86.111
    port: 8082
    name: tomcat_http
  - ip: 10.221.87.243
    port: 8444
    name: tomcat_https


