# Variables for DLVMMAXBRBSSDB01
# IP 10.221.86.218
---
# Add host-specific variables below
deploy_telegraf_redis: false
deploy_telegraf_postgres: false
deploy_telegraf_infra: false
deploy_mysql_replica_status_monitor: false
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false
deploy_mysql_slowquery_script: false
deploy_nginx: false

apps:
  - name: "mysql"
    match: "mysqld"
    type: "pattern"

# Application ports for DLVMMAXBRBSSDB01
ports:
  - ip: "10.221.86.218"
    port: 3306
    name: "mysql"
 