# Variables for DLVMAMXSAREACT01
# IP 10.221.92.55
---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "Node JS"
    match: "node server.js"
    type: "pattern"
	
  - name: "Node Exporter"
    match: "node_exporter"
    type: "pattern"    
# Application ports for DLVMAMXSAREACT01
ports:
  - ip: "127.0.0.1"
    port: 3001
    name: "node"

  - ip: "127.0.0.1"
    port: 8080
    name: "node"