# Variables for DLVMAMXDSBROCS01
---
# Add host-specific variables below
########## Feature Flags ##########
deploy_telegraf_redis: false
deploy_telegraf_postgres: false
deploy_telegraf_infra: false
deploy_mysql_replica_status_monitor: false
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false
deploy_mysql_slowquery_script: false
deploy_nginx: false
deploy_bssBypass_Check: true

#### Oracle DB details ######
oracle_home: /u01/app/oracle/product/11.2.4/client_1
db_user: RWUSER
db_pass: ROAMWARE
db_conn: RWDB

apps:
  - name: "Spread"
    match: "spread"
    type: "pattern"
  - name: "AirOCS"
    match: "AirOCSApp"
    type: "pattern"
  - name: "ApiService"
    match: "ApiServiceApp"
    type: "pattern"
  - name: "AirConsumer"
    match: "AirConsumerApp"
    type: "pattern"

ports:
  - ip: 127.0.0.1
    port: 4803
    name: spread
  - ip: 127.0.0.1
    port: 8080
    name: Java
  - ip: 127.0.0.1
    port: 2388
    name: java
  - ip: 127.0.0.1
    port: 8060
    name: Java
  - ip: 127.0.0.1
    port: 8005
    name: Java
  - ip: 127.0.0.1
    port: 8070
    name: Java
  - ip: 127.0.0.1
    port: 8009
    name: Java
  - ip: 10.221.87.133
    port: 1521
    name: Java
  - ip: 10.221.93.106
    port: 8086
    name: Java
  - ip: 10.221.93.107
    port: 8086
    name: Java
  - ip: 192.168.202.136
    port: 1556
    name: unknown
  - ip: 10.221.81.41
    port: 6667
    name: NN1
  - ip: 10.221.81.42
    port: 6667
    name: NN2
  - ip: 10.221.81.43
    port: 6667
    name: NN3
  - ip: 192.168.202.206
    port: 2049
    name: unknown
  - ip: 10.221.86.121
    port: 20131
    name: DRA
  - ip: 10.221.93.51
    port: 20131
    name: DRA
  - ip: 10.221.86.221
    port: 8080
    name: java
  - ip: 10.221.93.65
    port: 8080
    name: java

