# Variables for DLVMAMXALLBSS03
# IP 10.221.87.222
---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "BSS_Notification"
    match: "notification-0.1.jar"
    type: "pattern"

# Application ports for DLVMAMXALLBSS03
ports:
  - ip: "127.0.0.1"
    port: 8448
    name: "java"

  - ip: "10.221.81.41"
    port: 6667
    name: "KAFKA"