# Variables for DLVMAMXRECDRDB03
# IP 10.221.86.124

---
# Add host-specific variables below
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_dra_process_script: false

apps:
  - name: "mysqld"
    match: "mysqld"
    type: "pattern"

  - name: "CSVProcessorApp"
    match: "CSVProcessorApp"
    type: "pattern"

  
# Application ports for DLVMAMXRECDRDB03
ports:
  - ip: "127.0.0.1"
    port: 33060
    name: "mysqld"
	
  - ip: "127.0.0.1"
    port: 3306
    name: "mysqld"