# Variables for MIVMAMXSMSESIM01
---
deploy_telegraf_infra: false
deploy_app_metrics: true
deploy_port_listen_monitor: true
deploy_port_conn_monitor: true
deploy_ntp_status: false
deploy_telegraf_postgres: false
deploy_telegraf_redis: false
deploy_mysql_slowquery_script: false
deploy_mysql_replica_status_monitor: false
deploy_nginx: false
deploy_oracle_Metrics: true
deploy_dra_process_script: false

apps:
  - name: "cloudsimsmsc"
    match: "cloudsimsmsc"
    type: "pattern"

ports:
  - ip: "10.121.69.201"
    port: 1521
    name: "oracledb"

  - ip: "127.0.0.1"
    port: 8051
    name: "smsc"

