# Variables for all_servers
---
# Add host-specific variables below
#
########## Feature Flags ##########
deploy_telegraf_redis: false
deploy_telegraf_postgres: false
deploy_telegraf_infra: false
deploy_mysql_replica_status_monitor: false
deploy_mysql_slowquery_script: false
deploy_app_metrics: true
deploy_port_listen_monitor: false
deploy_port_conn_monitor: false
deploy_ntp_status: true
deploy_dra_process_script: false
deploy_nginx: false
deploy_bssBypass_Check: false

apps:
  - match: telegraf
    name: Telegraf
    type: "pattern"              # or "patter"

ports:
  - ip: 10.221.92.106
    port: 8086
    name: influx_Dallas1
  - ip: 10.221.92.107
    port: 8086
    name: influx_Dallas2
  - ip: 10.121.69.170
    port: 8086
    name: influx_Miami1
  - ip: 10.121.69.180
    port: 8086
    name: influx_Miami2