apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf-infra
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: telegraf-infra
  template:
    metadata:
      labels:
        app: telegraf-infra
    spec:
      serviceAccountName: telegraf
      containers:
      - name: telegraf
        image: telegraf:1.27
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
          requests:
            memory: "100Mi"
            cpu: "50m"
      volumes:
      - name: config
        configMap:
          name: telegraf-infra-config

